server:
  port: 8084
  servlet:
    context-path: /api/v1

spring:
  application:
    name: helpmeIud

  datasource:
    url: jdbc:mysql://localhost:3306/helpme_iud
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  mail:
    from: noreply@iudigital.edu.co
    host: smtp.gmail.com
    port: 587
    username: jonathan.garciaab@est.iudigital.edu.co
    password: jagb1102@
    properties:
      protocol: smtp
      auth: true
      starttls:
        enabled: true










